version: "3"
services:
  instarecipes:
    image: lordkener/instarecipes-app:latest
    restart: always
    ports:
      - "8443:8443"
    networks:
      - insta-network
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - insta-mysql
 
  insta-mysql:
    image: mysql:5.7
    restart: on-failure
    ports:
      - "3306:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    networks:
      - insta-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=instarecipes 
networks:
  insta-network: 